"""
Primary Verifier Agent: A crucial component of the "Two-Loop Verification" system.

This agent acts as a "Senior Developer on Code Review". Its primary responsibility is to
perform a static analysis of the code *specification* generated by the Architect,
*before* it gets passed to the Stitcher and Compiler.

By analyzing the `pure_code` and `decorators` together, it can anticipate a wide
range of errors (syntactical, logical, import-related) that would otherwise only
be caught much later in the pipeline, thus creating a very fast feedback loop.
"""
import pydantic
from typing import List, Optional

from project.core.llm_gateway.gateway import execute as llm_execute
from project.recipes.agents.architect import ArchitectOutput # To reuse the spec structure

class Input(pydantic.BaseModel):
    # Re-uses the Architect's output as its primary input
    architect_spec: ArchitectOutput
    # Optional feedback from the *Secondary* verifier from a previous full run
    secondary_verifier_feedback: Optional[str] = None
    model_group: Optional[str] = pydantic.Field("reasoning_model_group", description="The model group to use.")

class Output(pydantic.BaseModel):
    status: str # "success" or "error"
    feedback: Optional[str] = None # Detailed feedback for the Architect

async def execute_async(input_data: Input) -> Output:
    """
    Executes the static analysis of the code specification.
    """
    spec = input_data.architect_spec

    feedback_from_secondary = ""
    if input_data.secondary_verifier_feedback:
        feedback_from_secondary = f"""
        **CRITICAL CONTEXT FROM PREVIOUS RUN:**
        A previous version of this specification was fully compiled and run, but it failed the final verification step (Secondary Verifier).
        This means the code ran but had a logical flaw.
        Your primary goal is to ensure the new specification explicitly fixes this issue.

        **Previous Error:**
        ```
        {input_data.secondary_verifier_feedback}
        ```
        You MUST verify that the `pure_code` has been corrected to address this feedback.
        """

    prompt = f"""
    You are a Senior Code Mentor. Your goal is to help a Junior Developer (the Assembler) fix their code.
    You are reviewing a code **specification** that will be compiled.

    **Code Specification to Review:**

    **1. Decorators (if any):**
    ```json
    {spec.decorators}
    ```

    **2. Pure Business Logic Code:**
    ```python
    {spec.pure_code}
    ```
    {feedback_from_secondary}

    **Your Analysis Checklist:**
    1.  **Syntax & Imports:** Are all imports correct? (e.g. `from project.modules...`).
    2.  **Tool Usage:** Are the arguments for tools like `create_file` correct? (e.g. `path` and `content`).
    3.  **Logical Flow:** Does the code follow a logical sequence?

    **Your Output:**
    - If the code is solid and correct, respond with ONLY the word "Success".
    - If you find ANY error, you **MUST** provide constructive feedback starting with "Error:".
    - **CRITICAL:** In your feedback, provide the **Corrected Code Snippet** or specific instructions on how to fix the error. Help the Junior Developer learn.

    **Example Feedback:**
    Error: You are trying to use `create_file` without importing `CreateFileInput`.
    Fix: Add `from project.modules.filesystem.create_file import CreateFileInput` to your imports.
    """

    group_to_use = input_data.model_group if input_data.model_group else "reasoning_model_group"
    llm_response = await llm_execute(
        prompt=prompt,
        model_group=group_to_use
    )

    if "Success" in llm_response:
        return Output(status="success", feedback="Primary verifier approved the specification.")
    else:
        # The entire LLM response is the feedback
        return Output(status="error", feedback=llm_response)
